package cn.yfyue.sysauth.db.model;

public class BjArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_AREA.AREA_CODE
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_AREA.ADMIN_LEVEL
     *
     * @mbggenerated
     */
    private Integer areaLevel;

    public Integer getAreaLevel() {
		return areaLevel;
	}

	public void setAreaLevel(Integer areaLevel) {
		this.areaLevel = areaLevel;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_AREA.SUPPER_CODE
     *
     * @mbggenerated
     */
    private String supperCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_AREA.AREA_NAME
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_AREA.FULL_NAME
     *
     * @mbggenerated
     */
    private String fullName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_AREA.AREA_CODE
     *
     * @return the value of BJ_AREA.AREA_CODE
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_AREA.AREA_CODE
     *
     * @param areaCode the value for BJ_AREA.AREA_CODE
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_AREA.ADMIN_LEVEL
     *
     * @return the value of BJ_AREA.ADMIN_LEVEL
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_AREA.SUPPER_CODE
     *
     * @return the value of BJ_AREA.SUPPER_CODE
     *
     * @mbggenerated
     */
    public String getSupperCode() {
        return supperCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_AREA.SUPPER_CODE
     *
     * @param supperCode the value for BJ_AREA.SUPPER_CODE
     *
     * @mbggenerated
     */
    public void setSupperCode(String supperCode) {
        this.supperCode = supperCode == null ? null : supperCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_AREA.AREA_NAME
     *
     * @return the value of BJ_AREA.AREA_NAME
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_AREA.AREA_NAME
     *
     * @param areaName the value for BJ_AREA.AREA_NAME
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_AREA.FULL_NAME
     *
     * @return the value of BJ_AREA.FULL_NAME
     *
     * @mbggenerated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_AREA.FULL_NAME
     *
     * @param fullName the value for BJ_AREA.FULL_NAME
     *
     * @mbggenerated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }
}