package cn.yfyue.sysauth.db.model;

import java.io.UnsupportedEncodingException;
import java.util.Date;

public class BjHelpDoc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.DOC_ID
     *
     * @mbggenerated
     */
    private Long docId;
    private Long regMan;
    private String userName;
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Long getRegMan() {
		return regMan;
	}

	public void setRegMan(Long regMan) {
		this.regMan = regMan;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.DOC_TYPE
     *
     * @mbggenerated
     */
    private Integer docOrder;
    private String docCode;
    public String getDocCode() {
		return docCode;
	}

	public void setDocCode(String docCode) {
		this.docCode = docCode;
	}

	public Integer getDocOrder() {
		return docOrder;
	}

	public void setDocOrder(Integer docOrder) {
		this.docOrder = docOrder;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.DOC_TITLE
     *
     * @mbggenerated
     */
    private String docTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.DOC_STATE
     *
     * @mbggenerated
     */
    private Integer docState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.REG_TIME
     *
     * @mbggenerated
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.UP_TIME
     *
     * @mbggenerated
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.EXTEND_FIELD
     *
     * @mbggenerated
     */
    private String extendField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_HELP_DOC.DOC_CONTENT
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_HELP_DOC.DOC_ID
     *
     * @return the value of BJ_HELP_DOC.DOC_ID
     *
     * @mbggenerated
     */
    public Long getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_HELP_DOC.DOC_ID
     *
     * @param docId the value for BJ_HELP_DOC.DOC_ID
     *
     * @mbggenerated
     */
    public void setDocId(Long docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_HELP_DOC.DOC_TITLE
     *
     * @return the value of BJ_HELP_DOC.DOC_TITLE
     *
     * @mbggenerated
     */
    public String getDocTitle() {
        return docTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_HELP_DOC.DOC_TITLE
     *
     * @param docTitle the value for BJ_HELP_DOC.DOC_TITLE
     *
     * @mbggenerated
     */
    public void setDocTitle(String docTitle) {
        this.docTitle = docTitle == null ? null : docTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_HELP_DOC.DOC_STATE
     *
     * @return the value of BJ_HELP_DOC.DOC_STATE
     *
     * @mbggenerated
     */
    public Integer getDocState() {
        return docState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_HELP_DOC.DOC_STATE
     *
     * @param docState the value for BJ_HELP_DOC.DOC_STATE
     *
     * @mbggenerated
     */
    public void setDocState(Integer docState) {
        this.docState = docState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_HELP_DOC.REG_TIME
     *
     * @return the value of BJ_HELP_DOC.REG_TIME
     *
     * @mbggenerated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_HELP_DOC.REG_TIME
     *
     * @param regTime the value for BJ_HELP_DOC.REG_TIME
     *
     * @mbggenerated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_HELP_DOC.UP_TIME
     *
     * @return the value of BJ_HELP_DOC.UP_TIME
     *
     * @mbggenerated
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_HELP_DOC.UP_TIME
     *
     * @param upTime the value for BJ_HELP_DOC.UP_TIME
     *
     * @mbggenerated
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_HELP_DOC.EXTEND_FIELD
     *
     * @return the value of BJ_HELP_DOC.EXTEND_FIELD
     *
     * @mbggenerated
     */
    public String getExtendField() {
        return extendField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_HELP_DOC.EXTEND_FIELD
     *
     * @param extendField the value for BJ_HELP_DOC.EXTEND_FIELD
     *
     * @mbggenerated
     */
    public void setExtendField(String extendField) {
        this.extendField = extendField == null ? null : extendField.trim();
    }
    private String docContent;
    private byte[] docContentByte;
    public byte[] getDocContentByte() {
    	return docContentByte;
    }
    public String getDocContent() {
    	return docContent;
    }
    public void setDocContentByte(byte[] docContentByte) {
    	this.docContentByte = docContentByte;
    	try {
    		this.docContent = docContentByte == null || docContentByte.length == 0 ? null : new String(docContentByte, "UTF-8");
    	} catch (UnsupportedEncodingException e) {
    		e.printStackTrace();
    	}
    }

    public void setDocContent(String docContent) {
     this.docContent = docContent;
        try {
    		  this.docContentByte = docContent == null ? null : docContent.getBytes("UTF-8");
    		} catch (UnsupportedEncodingException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}
    }
}