package cn.yfyue.sysauth.db.model;

import java.util.Date;

public class BjLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.LOG_ID
     *
     * @mbggenerated
     */
    private Long logId;
    private String userName;
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.LOG_TYPE
     *
     * @mbggenerated
     */
    private Integer logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.LOGIN_NAME
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.OP_IP
     *
     * @mbggenerated
     */
    private String opIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.USER_ENVI
     *
     * @mbggenerated
     */
    private String userEnvi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.OP_TITLE
     *
     * @mbggenerated
     */
    private String opTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.CLASS_METHOD
     *
     * @mbggenerated
     */
    private String classMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.OP_PARA
     *
     * @mbggenerated
     */
    private String opPara;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.OP_FLAG
     *
     * @mbggenerated
     */
    private String opFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_LOG.LOG_TIME
     *
     * @mbggenerated
     */
    private Date logTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.LOG_ID
     *
     * @return the value of BJ_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.LOG_ID
     *
     * @param logId the value for BJ_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.LOG_TYPE
     *
     * @return the value of BJ_LOG.LOG_TYPE
     *
     * @mbggenerated
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.LOG_TYPE
     *
     * @param logType the value for BJ_LOG.LOG_TYPE
     *
     * @mbggenerated
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.LOGIN_NAME
     *
     * @return the value of BJ_LOG.LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.LOGIN_NAME
     *
     * @param loginName the value for BJ_LOG.LOGIN_NAME
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.OP_IP
     *
     * @return the value of BJ_LOG.OP_IP
     *
     * @mbggenerated
     */
    public String getOpIp() {
        return opIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.OP_IP
     *
     * @param opIp the value for BJ_LOG.OP_IP
     *
     * @mbggenerated
     */
    public void setOpIp(String opIp) {
        this.opIp = opIp == null ? null : opIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.USER_ENVI
     *
     * @return the value of BJ_LOG.USER_ENVI
     *
     * @mbggenerated
     */
    public String getUserEnvi() {
        return userEnvi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.USER_ENVI
     *
     * @param userEnvi the value for BJ_LOG.USER_ENVI
     *
     * @mbggenerated
     */
    public void setUserEnvi(String userEnvi) {
        this.userEnvi = userEnvi == null ? null : userEnvi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.OP_TITLE
     *
     * @return the value of BJ_LOG.OP_TITLE
     *
     * @mbggenerated
     */
    public String getOpTitle() {
        return opTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.OP_TITLE
     *
     * @param opTitle the value for BJ_LOG.OP_TITLE
     *
     * @mbggenerated
     */
    public void setOpTitle(String opTitle) {
        this.opTitle = opTitle == null ? null : opTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.CLASS_METHOD
     *
     * @return the value of BJ_LOG.CLASS_METHOD
     *
     * @mbggenerated
     */
    public String getClassMethod() {
        return classMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.CLASS_METHOD
     *
     * @param classMethod the value for BJ_LOG.CLASS_METHOD
     *
     * @mbggenerated
     */
    public void setClassMethod(String classMethod) {
        this.classMethod = classMethod == null ? null : classMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.OP_PARA
     *
     * @return the value of BJ_LOG.OP_PARA
     *
     * @mbggenerated
     */
    public String getOpPara() {
        return opPara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.OP_PARA
     *
     * @param opPara the value for BJ_LOG.OP_PARA
     *
     * @mbggenerated
     */
    public void setOpPara(String opPara) {
        this.opPara = opPara == null ? null : opPara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.OP_FLAG
     *
     * @return the value of BJ_LOG.OP_FLAG
     *
     * @mbggenerated
     */
    public String getOpFlag() {
        return opFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.OP_FLAG
     *
     * @param opFlag the value for BJ_LOG.OP_FLAG
     *
     * @mbggenerated
     */
    public void setOpFlag(String opFlag) {
        this.opFlag = opFlag == null ? null : opFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_LOG.LOG_TIME
     *
     * @return the value of BJ_LOG.LOG_TIME
     *
     * @mbggenerated
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_LOG.LOG_TIME
     *
     * @param logTime the value for BJ_LOG.LOG_TIME
     *
     * @mbggenerated
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }
}