package cn.yfyue.sysauth.db.model;

import java.util.Date;

public class BjRoleFun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE_FUN.ROLE_FUN_ID
     *
     * @mbggenerated
     */
    private Long roleFunId;
    private String funcName;
    private String funcUrl;
    private String funcState;
    private String supperFuncId;
    public String getFuncName() {
		return funcName;
	}

	public void setFuncName(String funcName) {
		this.funcName = funcName;
	}

	public String getFuncUrl() {
		return funcUrl;
	}

	public void setFuncUrl(String funcUrl) {
		this.funcUrl = funcUrl;
	}

	public String getFuncState() {
		return funcState;
	}

	public void setFuncState(String funcState) {
		this.funcState = funcState;
	}

	public String getSupperFuncId() {
		return supperFuncId;
	}

	public void setSupperFuncId(String supperFuncId) {
		this.supperFuncId = supperFuncId;
	}

	public String getIsLeaf() {
		return isLeaf;
	}

	public void setIsLeaf(String isLeaf) {
		this.isLeaf = isLeaf;
	}

	public String getFuncAlias() {
		return funcAlias;
	}

	public void setFuncAlias(String funcAlias) {
		this.funcAlias = funcAlias;
	}

	public String getFuncLevel() {
		return funcLevel;
	}

	public void setFuncLevel(String funcLevel) {
		this.funcLevel = funcLevel;
	}

	public String getStyleImg() {
		return styleImg;
	}

	public void setStyleImg(String styleImg) {
		this.styleImg = styleImg;
	}

	private String isLeaf;
    private String funcAlias;
    private String funcLevel;
    private String styleImg;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE_FUN.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE_FUN.FUN_ID
     *
     * @mbggenerated
     */
    private String funId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE_FUN.REG_MAN
     *
     * @mbggenerated
     */
    private Long regMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE_FUN.REG_TIME
     *
     * @mbggenerated
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE_FUN.ROLE_FUN_ID
     *
     * @return the value of BJ_ROLE_FUN.ROLE_FUN_ID
     *
     * @mbggenerated
     */
    public Long getRoleFunId() {
        return roleFunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE_FUN.ROLE_FUN_ID
     *
     * @param roleFunId the value for BJ_ROLE_FUN.ROLE_FUN_ID
     *
     * @mbggenerated
     */
    public void setRoleFunId(Long roleFunId) {
        this.roleFunId = roleFunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE_FUN.ROLE_ID
     *
     * @return the value of BJ_ROLE_FUN.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE_FUN.ROLE_ID
     *
     * @param roleId the value for BJ_ROLE_FUN.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE_FUN.FUN_ID
     *
     * @return the value of BJ_ROLE_FUN.FUN_ID
     *
     * @mbggenerated
     */
    public String getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE_FUN.FUN_ID
     *
     * @param funId the value for BJ_ROLE_FUN.FUN_ID
     *
     * @mbggenerated
     */
    public void setFunId(String funId) {
        this.funId = funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE_FUN.REG_MAN
     *
     * @return the value of BJ_ROLE_FUN.REG_MAN
     *
     * @mbggenerated
     */
    public Long getRegMan() {
        return regMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE_FUN.REG_MAN
     *
     * @param regMan the value for BJ_ROLE_FUN.REG_MAN
     *
     * @mbggenerated
     */
    public void setRegMan(Long regMan) {
        this.regMan = regMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE_FUN.REG_TIME
     *
     * @return the value of BJ_ROLE_FUN.REG_TIME
     *
     * @mbggenerated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE_FUN.REG_TIME
     *
     * @param regTime the value for BJ_ROLE_FUN.REG_TIME
     *
     * @mbggenerated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}