package cn.yfyue.sysauth.db.model;

import java.util.Date;

public class BjUserRole {
    @Override
	public String toString() {
		return "BjUserRole [userRoleId=" + userRoleId + ", userId=" + userId + ", roleId=" + roleId + ", upTime="
				+ upTime + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated
     */
    private Long userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_USER_ROLE.UP_TIME
     *
     * @mbggenerated
     */
    private Date upTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_USER_ROLE.USER_ROLE_ID
     *
     * @return the value of BJ_USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated
     */
    public Long getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_USER_ROLE.USER_ROLE_ID
     *
     * @param userRoleId the value for BJ_USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated
     */
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_USER_ROLE.USER_ID
     *
     * @return the value of BJ_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_USER_ROLE.USER_ID
     *
     * @param userId the value for BJ_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_USER_ROLE.ROLE_ID
     *
     * @return the value of BJ_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for BJ_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_USER_ROLE.UP_TIME
     *
     * @return the value of BJ_USER_ROLE.UP_TIME
     *
     * @mbggenerated
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_USER_ROLE.UP_TIME
     *
     * @param upTime the value for BJ_USER_ROLE.UP_TIME
     *
     * @mbggenerated
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }
}