package cn.yfyue.sysauth.db.model;

import java.util.Date;

public class BjFunc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.FUNC_ID
     *
     * @mbggenerated
     */
    private String funcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.FUNC_NAME
     *
     * @mbggenerated
     */
    private String funcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.FUNC_URL
     *
     * @mbggenerated
     */
    private String funcUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.FUNC_STATE
     *
     * @mbggenerated
     */
    private String funcState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.SUPPER_FUNC_ID
     *
     * @mbggenerated
     */
    private String supperFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.IS_LEAF
     *
     * @mbggenerated
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.FUNC_ALIAS
     *
     * @mbggenerated
     */
    private String funcAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.FUNC_LEVEL
     *
     * @mbggenerated
     */
    private Integer funcLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.STYLE_IMG
     *
     * @mbggenerated
     */
    private String styleImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.FUNC_ORDER
     *
     * @mbggenerated
     */
    private String funcOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.REG_MAN
     *
     * @mbggenerated
     */
    private String regMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_FUNC.REG_TIME
     *
     * @mbggenerated
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.FUNC_ID
     *
     * @return the value of BJ_FUNC.FUNC_ID
     *
     * @mbggenerated
     */
    public String getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.FUNC_ID
     *
     * @param funcId the value for BJ_FUNC.FUNC_ID
     *
     * @mbggenerated
     */
    public void setFuncId(String funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.FUNC_NAME
     *
     * @return the value of BJ_FUNC.FUNC_NAME
     *
     * @mbggenerated
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.FUNC_NAME
     *
     * @param funcName the value for BJ_FUNC.FUNC_NAME
     *
     * @mbggenerated
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.FUNC_URL
     *
     * @return the value of BJ_FUNC.FUNC_URL
     *
     * @mbggenerated
     */
    public String getFuncUrl() {
        return funcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.FUNC_URL
     *
     * @param funcUrl the value for BJ_FUNC.FUNC_URL
     *
     * @mbggenerated
     */
    public void setFuncUrl(String funcUrl) {
        this.funcUrl = funcUrl == null ? null : funcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.FUNC_STATE
     *
     * @return the value of BJ_FUNC.FUNC_STATE
     *
     * @mbggenerated
     */
    public String getFuncState() {
        return funcState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.FUNC_STATE
     *
     * @param funcState the value for BJ_FUNC.FUNC_STATE
     *
     * @mbggenerated
     */
    public void setFuncState(String funcState) {
        this.funcState = funcState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.SUPPER_FUNC_ID
     *
     * @return the value of BJ_FUNC.SUPPER_FUNC_ID
     *
     * @mbggenerated
     */
    public String getSupperFuncId() {
        return supperFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.SUPPER_FUNC_ID
     *
     * @param supperFuncId the value for BJ_FUNC.SUPPER_FUNC_ID
     *
     * @mbggenerated
     */
    public void setSupperFuncId(String supperFuncId) {
        this.supperFuncId = supperFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.IS_LEAF
     *
     * @return the value of BJ_FUNC.IS_LEAF
     *
     * @mbggenerated
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.IS_LEAF
     *
     * @param isLeaf the value for BJ_FUNC.IS_LEAF
     *
     * @mbggenerated
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.FUNC_ALIAS
     *
     * @return the value of BJ_FUNC.FUNC_ALIAS
     *
     * @mbggenerated
     */
    public String getFuncAlias() {
        return funcAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.FUNC_ALIAS
     *
     * @param funcAlias the value for BJ_FUNC.FUNC_ALIAS
     *
     * @mbggenerated
     */
    public void setFuncAlias(String funcAlias) {
        this.funcAlias = funcAlias == null ? null : funcAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.FUNC_LEVEL
     *
     * @return the value of BJ_FUNC.FUNC_LEVEL
     *
     * @mbggenerated
     */
    public Integer getFuncLevel() {
        return funcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.FUNC_LEVEL
     *
     * @param funcLevel the value for BJ_FUNC.FUNC_LEVEL
     *
     * @mbggenerated
     */
    public void setFuncLevel(Integer funcLevel) {
        this.funcLevel = funcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.STYLE_IMG
     *
     * @return the value of BJ_FUNC.STYLE_IMG
     *
     * @mbggenerated
     */
    public String getStyleImg() {
        return styleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.STYLE_IMG
     *
     * @param styleImg the value for BJ_FUNC.STYLE_IMG
     *
     * @mbggenerated
     */
    public void setStyleImg(String styleImg) {
        this.styleImg = styleImg == null ? null : styleImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.FUNC_ORDER
     *
     * @return the value of BJ_FUNC.FUNC_ORDER
     *
     * @mbggenerated
     */
    public String getFuncOrder() {
        return funcOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.FUNC_ORDER
     *
     * @param funcOrder the value for BJ_FUNC.FUNC_ORDER
     *
     * @mbggenerated
     */
    public void setFuncOrder(String funcOrder) {
        this.funcOrder = funcOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.REG_MAN
     *
     * @return the value of BJ_FUNC.REG_MAN
     *
     * @mbggenerated
     */
    public String getRegMan() {
        return regMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.REG_MAN
     *
     * @param regMan the value for BJ_FUNC.REG_MAN
     *
     * @mbggenerated
     */
    public void setRegMan(String regMan) {
        this.regMan = regMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_FUNC.REG_TIME
     *
     * @return the value of BJ_FUNC.REG_TIME
     *
     * @mbggenerated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_FUNC.REG_TIME
     *
     * @param regTime the value for BJ_FUNC.REG_TIME
     *
     * @mbggenerated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}