package cn.yfyue.sysauth.db.model;

import java.util.Date;

public class BjRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private Long roleId;
    private String orgeFullName;
    public String getOrgeFullName() {
		return orgeFullName;
	}

	public void setOrgeFullName(String orgeFullName) {
		this.orgeFullName = orgeFullName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE.ROLE_KEY
     *
     * @mbggenerated
     */
    private String roleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE.ROLE_STATE
     *
     * @mbggenerated
     */
    private Integer roleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BJ_ROLE.UP_TIME
     *
     * @mbggenerated
     */
    private Date upTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE.ROLE_ID
     *
     * @return the value of BJ_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE.ROLE_ID
     *
     * @param roleId the value for BJ_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE.ROLE_NAME
     *
     * @return the value of BJ_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE.ROLE_NAME
     *
     * @param roleName the value for BJ_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE.ROLE_KEY
     *
     * @return the value of BJ_ROLE.ROLE_KEY
     *
     * @mbggenerated
     */
    public String getRoleKey() {
        return roleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE.ROLE_KEY
     *
     * @param roleKey the value for BJ_ROLE.ROLE_KEY
     *
     * @mbggenerated
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey == null ? null : roleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE.ROLE_STATE
     *
     * @return the value of BJ_ROLE.ROLE_STATE
     *
     * @mbggenerated
     */
    public Integer getRoleState() {
        return roleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE.ROLE_STATE
     *
     * @param roleState the value for BJ_ROLE.ROLE_STATE
     *
     * @mbggenerated
     */
    public void setRoleState(Integer roleState) {
        this.roleState = roleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BJ_ROLE.UP_TIME
     *
     * @return the value of BJ_ROLE.UP_TIME
     *
     * @mbggenerated
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BJ_ROLE.UP_TIME
     *
     * @param upTime the value for BJ_ROLE.UP_TIME
     *
     * @mbggenerated
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }
}