package cn.yfyue.lxc.db.model;

import java.util.Date;

public class Dongguan   {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.MID
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_NAME
     *
     * @mbggenerated
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_ADDRESS
     *
     * @mbggenerated
     */
    private String mAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_TYPE
     *
     * @mbggenerated
     */
    private String mType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_APPOINTEDYIME
     *
     * @mbggenerated
     */
    private Date mAppointedyime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_TOGONO
     *
     * @mbggenerated
     */
    private String mTogono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_TOTHETIME
     *
     * @mbggenerated
     */
    private String mTothetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_COMPANY_TEL
     *
     * @mbggenerated
     */
    private String mCompanyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_RESULT
     *
     * @mbggenerated
     */
    private String mResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dongguan.M_FEEL
     *
     * @mbggenerated
     */
    private String mFeel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.MID
     *
     * @return the value of dongguan.MID
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.MID
     *
     * @param mid the value for dongguan.MID
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_NAME
     *
     * @return the value of dongguan.M_NAME
     *
     * @mbggenerated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_NAME
     *
     * @param mName the value for dongguan.M_NAME
     *
     * @mbggenerated
     */
    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_ADDRESS
     *
     * @return the value of dongguan.M_ADDRESS
     *
     * @mbggenerated
     */
    public String getmAddress() {
        return mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_ADDRESS
     *
     * @param mAddress the value for dongguan.M_ADDRESS
     *
     * @mbggenerated
     */
    public void setmAddress(String mAddress) {
        this.mAddress = mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_TYPE
     *
     * @return the value of dongguan.M_TYPE
     *
     * @mbggenerated
     */
    public String getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_TYPE
     *
     * @param mType the value for dongguan.M_TYPE
     *
     * @mbggenerated
     */
    public void setmType(String mType) {
        this.mType = mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_APPOINTEDYIME
     *
     * @return the value of dongguan.M_APPOINTEDYIME
     *
     * @mbggenerated
     */
    public Date getmAppointedyime() {
        return mAppointedyime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_APPOINTEDYIME
     *
     * @param mAppointedyime the value for dongguan.M_APPOINTEDYIME
     *
     * @mbggenerated
     */
    public void setmAppointedyime(Date mAppointedyime) {
        this.mAppointedyime = mAppointedyime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_TOGONO
     *
     * @return the value of dongguan.M_TOGONO
     *
     * @mbggenerated
     */
    public String getmTogono() {
        return mTogono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_TOGONO
     *
     * @param mTogono the value for dongguan.M_TOGONO
     *
     * @mbggenerated
     */
    public void setmTogono(String mTogono) {
        this.mTogono = mTogono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_TOTHETIME
     *
     * @return the value of dongguan.M_TOTHETIME
     *
     * @mbggenerated
     */
    public String getmTothetime() {
        return mTothetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_TOTHETIME
     *
     * @param mTothetime the value for dongguan.M_TOTHETIME
     *
     * @mbggenerated
     */
    public void setmTothetime(String mTothetime) {
        this.mTothetime = mTothetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_COMPANY_TEL
     *
     * @return the value of dongguan.M_COMPANY_TEL
     *
     * @mbggenerated
     */
    public String getmCompanyTel() {
        return mCompanyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_COMPANY_TEL
     *
     * @param mCompanyTel the value for dongguan.M_COMPANY_TEL
     *
     * @mbggenerated
     */
    public void setmCompanyTel(String mCompanyTel) {
        this.mCompanyTel = mCompanyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_RESULT
     *
     * @return the value of dongguan.M_RESULT
     *
     * @mbggenerated
     */
    public String getmResult() {
        return mResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_RESULT
     *
     * @param mResult the value for dongguan.M_RESULT
     *
     * @mbggenerated
     */
    public void setmResult(String mResult) {
        this.mResult = mResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dongguan.M_FEEL
     *
     * @return the value of dongguan.M_FEEL
     *
     * @mbggenerated
     */
    public String getmFeel() {
        return mFeel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dongguan.M_FEEL
     *
     * @param mFeel the value for dongguan.M_FEEL
     *
     * @mbggenerated
     */
    public void setmFeel(String mFeel) {
        this.mFeel = mFeel;
    }
}