package cn.yfyue.lxc.db.model;

import java.util.Date;

public class Hangzhou {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_ID
     *
     * @mbggenerated
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_NAME
     *
     * @mbggenerated
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_ADDRESS
     *
     * @mbggenerated
     */
    private String mAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_MDATE
     *
     * @mbggenerated
     */
    private Date mMdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_TYPE
     *
     * @mbggenerated
     */
    private String mType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_EDUCATION
     *
     * @mbggenerated
     */
    private String mEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_DISTANCE
     *
     * @mbggenerated
     */
    private String mDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_PHONE
     *
     * @mbggenerated
     */
    private String mPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_RESULT
     *
     * @mbggenerated
     */
    private String mResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hangzhou.M_FEEL
     *
     * @mbggenerated
     */
    private String mFeel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_ID
     *
     * @return the value of hangzhou.M_ID
     *
     * @mbggenerated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_ID
     *
     * @param mId the value for hangzhou.M_ID
     *
     * @mbggenerated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_NAME
     *
     * @return the value of hangzhou.M_NAME
     *
     * @mbggenerated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_NAME
     *
     * @param mName the value for hangzhou.M_NAME
     *
     * @mbggenerated
     */
    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_ADDRESS
     *
     * @return the value of hangzhou.M_ADDRESS
     *
     * @mbggenerated
     */
    public String getmAddress() {
        return mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_ADDRESS
     *
     * @param mAddress the value for hangzhou.M_ADDRESS
     *
     * @mbggenerated
     */
    public void setmAddress(String mAddress) {
        this.mAddress = mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_MDATE
     *
     * @return the value of hangzhou.M_MDATE
     *
     * @mbggenerated
     */
    public Date getmMdate() {
        return mMdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_MDATE
     *
     * @param mMdate the value for hangzhou.M_MDATE
     *
     * @mbggenerated
     */
    public void setmMdate(Date mMdate) {
        this.mMdate = mMdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_TYPE
     *
     * @return the value of hangzhou.M_TYPE
     *
     * @mbggenerated
     */
    public String getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_TYPE
     *
     * @param mType the value for hangzhou.M_TYPE
     *
     * @mbggenerated
     */
    public void setmType(String mType) {
        this.mType = mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_EDUCATION
     *
     * @return the value of hangzhou.M_EDUCATION
     *
     * @mbggenerated
     */
    public String getmEducation() {
        return mEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_EDUCATION
     *
     * @param mEducation the value for hangzhou.M_EDUCATION
     *
     * @mbggenerated
     */
    public void setmEducation(String mEducation) {
        this.mEducation = mEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_DISTANCE
     *
     * @return the value of hangzhou.M_DISTANCE
     *
     * @mbggenerated
     */
    public String getmDistance() {
        return mDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_DISTANCE
     *
     * @param mDistance the value for hangzhou.M_DISTANCE
     *
     * @mbggenerated
     */
    public void setmDistance(String mDistance) {
        this.mDistance = mDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_PHONE
     *
     * @return the value of hangzhou.M_PHONE
     *
     * @mbggenerated
     */
    public String getmPhone() {
        return mPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_PHONE
     *
     * @param mPhone the value for hangzhou.M_PHONE
     *
     * @mbggenerated
     */
    public void setmPhone(String mPhone) {
        this.mPhone = mPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_RESULT
     *
     * @return the value of hangzhou.M_RESULT
     *
     * @mbggenerated
     */
    public String getmResult() {
        return mResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_RESULT
     *
     * @param mResult the value for hangzhou.M_RESULT
     *
     * @mbggenerated
     */
    public void setmResult(String mResult) {
        this.mResult = mResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hangzhou.M_FEEL
     *
     * @return the value of hangzhou.M_FEEL
     *
     * @mbggenerated
     */
    public String getmFeel() {
        return mFeel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hangzhou.M_FEEL
     *
     * @param mFeel the value for hangzhou.M_FEEL
     *
     * @mbggenerated
     */
    public void setmFeel(String mFeel) {
        this.mFeel = mFeel;
    }
}